{% set name = "eigenpy" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stack-of-tasks/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e2b2c3cd78f163f4d96bee008124ebe3369c6bab8db3c055c1cb239e49835b7

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - clang  # [win]
    - make  # [not win]
    - ninja  # [win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - eigen
    - boost
    - numpy
    - python
  run:
    - eigen
    - boost
    - {{ pin_compatible('numpy') }}
    - python

test:
  requires:
    - pkg-config
    - boost
  imports:
    - eigenpy
  commands:
    - pkg-config --modversion eigenpy

about:
  home: http://github.com/stack-of-tasks/eigenpy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bindings between Numpy and Eigen using Boost.Python
  dev_url: https://github.com/stack-of-tasks/eigenpy

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - seanyen
